### ISSUE TITLE
inference not working

### ISSUE THREAD

**Issue by PA0ZHB** [DT42/BerryNet#21]
HI, the snapshots in jpg and json are in dir /usr/local/berrynet, NOT in inference/image 
i installed many times in my rpi3 with stretch.
the log says : Unsubscribed topic berrynet/action/log
no errors in the log or status report.
i have LINE  in berrynet-manager disabled.

(i like to use berrynet with the Movidium stick)

i hope someone helps me out..

**Comment by bafu** [comment]
@PA0ZHB Inference result image and text appeared in `/usr/local/berrynet` because data collector service was enabled by default, and the storage directory was kept as default in `/usr/local/berrynet/config.js`.

For inference issue, please try the [v2.3.0 installation image](https://github.com/DT42/BerryNet/releases/tag/v2.3.0) w/o building from scratch.
