### ISSUE TITLE
Error in updating the pkg or installing 

### ISSUE THREAD

**Issue by ripgamer** [DT42/BerryNet#38]
$ apt-get update or $ pkg update 
Ign:1 http://dl.bintray.com/xeffyr/unstable-packages-21 unstable InRelease
Err:2 http://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release
  404  Not Found [IP: 34.217.163.1 80]
Hit:3 https://termux.net stable InRelease
Ign:4 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:5 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:6 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:8 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:8 https://dl.bintray.com/grimler/science-packages-21 science Release
Reading package lists... Done
E: The repository 'http://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by bafu** [comment]
@ripgamer This is not a BerryNet issue, but I'm happy to help.

You meet the error message because `http://dl.bintray.com/xeffyr/unstable-packages-21` is not valid (access the link and will get "Repository path missing or not specified").

To fix it, you can

1. Check your sources.list files and find `http://dl.bintray.com/xeffyr/unstable-packages-21`
1. Comment out `http://dl.bintray.com/xeffyr/unstable-packages-21`
1. Run `apt update`
