### ISSUE TITLE
Regarding tensorflow on manual installation

### ISSUE THREAD

**Issue by MohaBeacon** [DT42/BerryNet#56]
Berrynet on manual installation

after ./configure command,

the supervisor is not running camera and tflite

while checking logs shows,

tensorflow is not installed during ./configure

**Comment by bafu** [comment]
@MohaBeacon Thank you for the issue report.

**Root Cause**

The upstream moves TF Python Wheels from GitHub to GDrive, and it affects all the download links.

**Solution**

You can download and install the TF Wheel manually before we fix this issue.

1. Download the TF Wheel by running the [upstream's script](https://github.com/PINTO0309/Tensorflow-bin/blob/master/tensorflow-1.15.0-cp37-cp37m-linux_armv7l_download.sh)
1. Install the Wheel manually

        $ python3 -m pip install tensorflow-1.15.0-cp37-cp37m-linux_armv7l.whl
